[project]
name = "house-prediction"
version = "0.1.0"
description = ""
authors = [
    {name = "Yusuf Raheem",email = "yusufraheem500@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "scikit-learn (>=1.9.0,<2.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "duckdb (>=1.5.5,<2.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "duckdb-engine (>=0.17.0,<0.18.0)",
    "wemake-python-styleguide (>=1.8.1,<2.0.0)",
    "ruff (>=0.16.8,<0.17.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [
    "src/config/__init__.py",
    "src/config/.env",
    "src/db/db.duckdb",
    "src/logs",
    "src/model/models",
    "src/Data/data_prep.ipynb",
    "intference_service/app/config/__init__.py"
]

[tool.ruff.lint.per-file-ignores]
"inference_service/app/config/__init__.py" = ["F401"]
"src/config/__init__.py" = ["F401"]
